# This file was generated by the `rails generate rspec:install` command, and
# will likely be overridden by the next rails generate command. Please do not
# edit this file. Instead, edit the `.rspec` file to configure RSpec.

require 'rails_helper' 